<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['code' => 'ABW', 'country' => 'ARUBA', 'sort_order' => 1],
            ['code' => 'AFG', 'country' => 'AFGHANISTAN', 'sort_order' => 2],
            ['code' => 'AGO', 'country' => 'ANGOLA', 'sort_order' => 3],
            ['code' => 'AIA', 'country' => 'ANGUILLA', 'sort_order' => 4],
            ['code' => 'ALA', 'country' => 'ALAND ISLANDS', 'sort_order' => 5],
            ['code' => 'ALB', 'country' => 'ALBANIA', 'sort_order' => 6],
            ['code' => 'AND', 'country' => 'ANDORA', 'sort_order' => 7],
            ['code' => 'ANT', 'country' => 'NETHERLANDS ANTILLES', 'sort_order' => 8],
            ['code' => 'ARE', 'country' => 'UNITED ARAB EMIRATES', 'sort_order' => 9],
            ['code' => 'ARG', 'country' => 'ARGENTINA', 'sort_order' => 10],
            ['code' => 'ARM', 'country' => 'ARMENIA', 'sort_order' => 11],
            ['code' => 'ASM', 'country' => 'AMERICAN SAMOA', 'sort_order' => 12],
            ['code' => 'ATA', 'country' => 'ANTARCTICA', 'sort_order' => 13],
            ['code' => 'ATF', 'country' => 'FRENCH SOUTHERN TERRITORIES', 'sort_order' => 14],
            ['code' => 'ATG', 'country' => 'ANTIGUA AND BARBUDA', 'sort_order' => 15],
            ['code' => 'AUS', 'country' => 'AUSTRALIA', 'sort_order' => 16],
            ['code' => 'AUT', 'country' => 'AUSTRIA', 'sort_order' => 17],
            ['code' => 'AZE', 'country' => 'AZERBAIDJAN', 'sort_order' => 18],
            ['code' => 'BDI', 'country' => 'BURUNDI', 'sort_order' => 19],
            ['code' => 'BEL', 'country' => 'BELGIUM', 'sort_order' => 20],
            ['code' => 'BEN', 'country' => 'BENIN', 'sort_order' => 21],
            ['code' => 'BES', 'country' => 'BONAIRE, SINT EUSTATIUS AND SABA', 'sort_order' => 22],
            ['code' => 'BFA', 'country' => 'BURKINA FASO', 'sort_order' => 23],
            ['code' => 'BGD', 'country' => 'BANGLADESH', 'sort_order' => 24],
            ['code' => 'BGR', 'country' => 'BULGARIA', 'sort_order' => 25],
            ['code' => 'BHR', 'country' => 'BAHRAIN', 'sort_order' => 26],
            ['code' => 'BHS', 'country' => 'BAHAMAS', 'sort_order' => 27],
            ['code' => 'BIH', 'country' => 'BOSNIA AND HERZEGOVINA', 'sort_order' => 28],
            ['code' => 'BLM', 'country' => 'SAINT BARTHELEMY', 'sort_order' => 29],
            ['code' => 'BLR', 'country' => 'BELARUS', 'sort_order' => 30],
            ['code' => 'BLZ', 'country' => 'BELIZE', 'sort_order' => 31],
            ['code' => 'BMU', 'country' => 'BERMUDA', 'sort_order' => 32],
            ['code' => 'BOL', 'country' => 'BOLIVIA', 'sort_order' => 33],
            ['code' => 'BRA', 'country' => 'BRAZIL', 'sort_order' => 34],
            ['code' => 'BRB', 'country' => 'BARBADOS', 'sort_order' => 35],
            ['code' => 'BRN', 'country' => 'BRUNEI DARUSSALAM', 'sort_order' => 36],
            ['code' => 'BTN', 'country' => 'BHUTAN', 'sort_order' => 37],
            ['code' => 'BVT', 'country' => 'BOUVET ISLAND', 'sort_order' => 38],
            ['code' => 'BWA', 'country' => 'BOTSWANA', 'sort_order' => 39],
            ['code' => 'CAF', 'country' => 'CENTRAL AFRICAN REPUBLIC', 'sort_order' => 40],
            ['code' => 'CAN', 'country' => 'CANADA', 'sort_order' => 41],
            ['code' => 'CCK', 'country' => 'COCOS ISLAND', 'sort_order' => 42],
            ['code' => 'CHE', 'country' => 'SWITZERLAND', 'sort_order' => 43],
            ['code' => 'CHL', 'country' => 'CHILE', 'sort_order' => 44],
            ['code' => 'CHN', 'country' => 'CHINA', 'sort_order' => 45],
            ['code' => 'CIV', 'country' => 'COTE D\'IVOIRE', 'sort_order' => 46],
            ['code' => 'CMR', 'country' => 'CAMEROON', 'sort_order' => 47],
            ['code' => 'COD', 'country' => 'CONGO, THE DEMOCRATIC REPUBLIC', 'sort_order' => 48],
            ['code' => 'COG', 'country' => 'CONGO', 'sort_order' => 49],
            ['code' => 'COK', 'country' => 'COOK ISLANDS', 'sort_order' => 50],
            ['code' => 'COL', 'country' => 'COLOMBIA', 'sort_order' => 51],
            ['code' => 'COM', 'country' => 'COMOROS', 'sort_order' => 52],
            ['code' => 'CPV', 'country' => 'CABO VERDE', 'sort_order' => 53],
            ['code' => 'CRI', 'country' => 'COSTA RICA', 'sort_order' => 54],
            ['code' => 'CRM', 'country' => 'CRIMEA', 'sort_order' => 55],
            ['code' => 'CUB', 'country' => 'CUBA', 'sort_order' => 56],
            ['code' => 'CUW', 'country' => 'CURACAO', 'sort_order' => 57],
            ['code' => 'CXR', 'country' => 'CHRISTMAS ISLANDS', 'sort_order' => 58],
            ['code' => 'CYM', 'country' => 'CAYMAN ISLANDS', 'sort_order' => 59],
            ['code' => 'CYP', 'country' => 'CYPRUS', 'sort_order' => 60],
            ['code' => 'CZE', 'country' => 'CZECH REPUBLIC', 'sort_order' => 61],
            ['code' => 'DEU', 'country' => 'GERMANY', 'sort_order' => 62],
            ['code' => 'DJI', 'country' => 'DJIBOUTI', 'sort_order' => 63],
            ['code' => 'DMA', 'country' => 'DOMINICA', 'sort_order' => 64],
            ['code' => 'DNK', 'country' => 'DENMARK', 'sort_order' => 65],
            ['code' => 'DOM', 'country' => 'DOMINICAN REPUBLIC', 'sort_order' => 66],
            ['code' => 'DZA', 'country' => 'ALGERIA', 'sort_order' => 67],
            ['code' => 'ECU', 'country' => 'ECUADOR', 'sort_order' => 68],
            ['code' => 'EGY', 'country' => 'EGYPT', 'sort_order' => 69],
            ['code' => 'ERI', 'country' => 'ERITREA', 'sort_order' => 70],
            ['code' => 'ESH', 'country' => 'WESTERN SAHARA', 'sort_order' => 71],
            ['code' => 'ESP', 'country' => 'SPAIN', 'sort_order' => 72],
            ['code' => 'EST', 'country' => 'ESTONIA', 'sort_order' => 73],
            ['code' => 'ETH', 'country' => 'ETHIOPIA', 'sort_order' => 74],
            ['code' => 'FIN', 'country' => 'FINLAND', 'sort_order' => 75],
            ['code' => 'FJI', 'country' => 'FIJI', 'sort_order' => 76],
            ['code' => 'FLK', 'country' => 'FALKLAND ISLANDS (MALVINAS)', 'sort_order' => 77],
            ['code' => 'FRA', 'country' => 'FRANCE', 'sort_order' => 78],
            ['code' => 'FRO', 'country' => 'FAEROE ISLANDS', 'sort_order' => 79],
            ['code' => 'FSM', 'country' => 'MICRONESIA, FEDERATED STATES OF', 'sort_order' => 80],
            ['code' => 'GAB', 'country' => 'GABON', 'sort_order' => 81],
            ['code' => 'GBR', 'country' => 'UNITED KINGDOM', 'sort_order' => 82],
            ['code' => 'GEO', 'country' => 'GEORGIA', 'sort_order' => 83],
            ['code' => 'GGY', 'country' => 'GUERNSEY', 'sort_order' => 84],
            ['code' => 'GHA', 'country' => 'GHANA', 'sort_order' => 85],
            ['code' => 'GIB', 'country' => 'GIBRALTAR', 'sort_order' => 86],
            ['code' => 'GIN', 'country' => 'GUINEA', 'sort_order' => 87],
            ['code' => 'GLP', 'country' => 'GUADELOUPE', 'sort_order' => 88],
            ['code' => 'GMB', 'country' => 'GAMBIA', 'sort_order' => 89],
            ['code' => 'GNB', 'country' => 'GUINEA-BISSAU', 'sort_order' => 90],
            ['code' => 'GNQ', 'country' => 'EQUATORIAL GUINEA', 'sort_order' => 91],
            ['code' => 'GRC', 'country' => 'GREECE', 'sort_order' => 92],
            ['code' => 'GRD', 'country' => 'GRENADA', 'sort_order' => 93],
            ['code' => 'GRL', 'country' => 'GREENLAND', 'sort_order' => 94],
            ['code' => 'GTM', 'country' => 'GUATEMALA', 'sort_order' => 95],
            ['code' => 'GUF', 'country' => 'FRENCH GUIANA', 'sort_order' => 96],
            ['code' => 'GUM', 'country' => 'GUAM', 'sort_order' => 97],
            ['code' => 'GUY', 'country' => 'GUYANA', 'sort_order' => 98],
            ['code' => 'HKG', 'country' => 'HONG KONG', 'sort_order' => 99],
            ['code' => 'HMD', 'country' => 'HEARD AND MCDONALD ISLANDS', 'sort_order' => 100],
            ['code' => 'HND', 'country' => 'HONDURAS', 'sort_order' => 101],
            ['code' => 'HRV', 'country' => 'CROATIA', 'sort_order' => 102],
            ['code' => 'HTI', 'country' => 'HAITI', 'sort_order' => 103],
            ['code' => 'HUN', 'country' => 'HUNGARY', 'sort_order' => 104],
            ['code' => 'IDN', 'country' => 'INDONESIA', 'sort_order' => 105],
            ['code' => 'IMN', 'country' => 'ISLE OF MAN', 'sort_order' => 106],
            ['code' => 'IND', 'country' => 'INDIA', 'sort_order' => 107],
            ['code' => 'IOT', 'country' => 'BRITISH INDIAN OCEAN TERRITORY', 'sort_order' => 108],
            ['code' => 'IRL', 'country' => 'IRELAND', 'sort_order' => 109],
            ['code' => 'IRN', 'country' => 'IRAN', 'sort_order' => 110],
            ['code' => 'IRQ', 'country' => 'IRAQ', 'sort_order' => 111],
            ['code' => 'ISL', 'country' => 'ICELAND', 'sort_order' => 112],
            ['code' => 'ISR', 'country' => 'ISRAEL', 'sort_order' => 113],
            ['code' => 'ITA', 'country' => 'ITALY', 'sort_order' => 114],
            ['code' => 'JAM', 'country' => 'JAMAICA', 'sort_order' => 115],
            ['code' => 'JEY', 'country' => 'JERSEY (CHANNEL ISLANDS)', 'sort_order' => 116],
            ['code' => 'JOR', 'country' => 'JORDAN', 'sort_order' => 117],
            ['code' => 'JPN', 'country' => 'JAPAN', 'sort_order' => 118],
            ['code' => 'KAZ', 'country' => 'KAZAKHSTAN', 'sort_order' => 119],
            ['code' => 'KEN', 'country' => 'KENYA', 'sort_order' => 120],
            ['code' => 'KGZ', 'country' => 'KYRGYZSTAN', 'sort_order' => 121],
            ['code' => 'KHM', 'country' => 'CAMBODIA', 'sort_order' => 122],
            ['code' => 'KIR', 'country' => 'KIRIBATI', 'sort_order' => 123],
            ['code' => 'KNA', 'country' => 'ST.KITTS AND NEVIS', 'sort_order' => 124],
            ['code' => 'KOR', 'country' => 'THE REPUBLIC OF KOREA', 'sort_order' => 125],
            ['code' => 'KWT', 'country' => 'KUWAIT', 'sort_order' => 126],
            ['code' => 'LAO', 'country' => 'LAOS', 'sort_order' => 127],
            ['code' => 'LBN', 'country' => 'LEBANON', 'sort_order' => 128],
            ['code' => 'LBR', 'country' => 'LIBERIA', 'sort_order' => 129],
            ['code' => 'LBY', 'country' => 'LIBYAN ARAB JAMAHIRIYA', 'sort_order' => 130],
            ['code' => 'LCA', 'country' => 'SAINT LUCIA', 'sort_order' => 131],
            ['code' => 'LIE', 'country' => 'LIECHTENSTEIN', 'sort_order' => 132],
            ['code' => 'LKA', 'country' => 'SRI LANKA', 'sort_order' => 133],
            ['code' => 'LSO', 'country' => 'LESOTHO', 'sort_order' => 134],
            ['code' => 'LTU', 'country' => 'LITHUANIA', 'sort_order' => 135],
            ['code' => 'LUX', 'country' => 'LUXEMBOURG', 'sort_order' => 136],
            ['code' => 'LVA', 'country' => 'LATVIA', 'sort_order' => 137],
            ['code' => 'MAC', 'country' => 'MACAO', 'sort_order' => 138],
            ['code' => 'MAF', 'country' => 'SAINT MARTIN (FRENCH PART)', 'sort_order' => 139],
            ['code' => 'MAR', 'country' => 'MOROCCO', 'sort_order' => 140],
            ['code' => 'MCO', 'country' => 'MONACO', 'sort_order' => 141],
            ['code' => 'MDA', 'country' => 'MOLDOVA, REPUBLIC OF', 'sort_order' => 142],
            ['code' => 'MDG', 'country' => 'MADAGASCAR', 'sort_order' => 143],
            ['code' => 'MDV', 'country' => 'MALDIVES', 'sort_order' => 144],
            ['code' => 'MEX', 'country' => 'MEXICO', 'sort_order' => 145],
            ['code' => 'MHL', 'country' => 'MARSHALL ISLANDS', 'sort_order' => 146],
            ['code' => 'MKD', 'country' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'sort_order' => 147],
            ['code' => 'MLI', 'country' => 'MALI', 'sort_order' => 148],
            ['code' => 'MLT', 'country' => 'MALTA', 'sort_order' => 149],
            ['code' => 'MMR', 'country' => 'MYANMAR', 'sort_order' => 150],
            ['code' => 'MNE', 'country' => 'MONTENEGRO', 'sort_order' => 151],
            ['code' => 'MNG', 'country' => 'MONGOLIA', 'sort_order' => 152],
            ['code' => 'MNP', 'country' => 'NORTHERN MARIANA ISLANDS', 'sort_order' => 153],
            ['code' => 'MOZ', 'country' => 'MOZAMBIQUE', 'sort_order' => 154],
            ['code' => 'MRT', 'country' => 'MAURITANIA', 'sort_order' => 155],
            ['code' => 'MSR', 'country' => 'MONTSERRAT', 'sort_order' => 156],
            ['code' => 'MTQ', 'country' => 'MARTINIQUE', 'sort_order' => 157],
            ['code' => 'MUS', 'country' => 'MAURITIUS', 'sort_order' => 158],
            ['code' => 'MWI', 'country' => 'MALAWI', 'sort_order' => 159],
            ['code' => 'MYS', 'country' => 'MALAYSIA', 'sort_order' => 160],
            ['code' => 'MYT', 'country' => 'MAYOTTE', 'sort_order' => 161],
            ['code' => 'NAM', 'country' => 'NAMIBIA', 'sort_order' => 162],
            ['code' => 'NCL', 'country' => 'NEW CALEDONIA', 'sort_order' => 163],
            ['code' => 'NER', 'country' => 'NIGER', 'sort_order' => 164],
            ['code' => 'NFK', 'country' => 'NORFOLK ISLAND', 'sort_order' => 165],
            ['code' => 'NGA', 'country' => 'NIGERIA', 'sort_order' => 166],
            ['code' => 'NIC', 'country' => 'NICARAGUA', 'sort_order' => 167],
            ['code' => 'NIU', 'country' => 'NIUE', 'sort_order' => 168],
            ['code' => 'NLD', 'country' => 'NETHERLANDS', 'sort_order' => 169],
            ['code' => 'NOR', 'country' => 'NORWAY', 'sort_order' => 170],
            ['code' => 'NPL', 'country' => 'NEPAL', 'sort_order' => 171],
            ['code' => 'NRU', 'country' => 'NAURU', 'sort_order' => 172],
            ['code' => 'NZL', 'country' => 'NEW ZEALAND', 'sort_order' => 173],
            ['code' => 'OMN', 'country' => 'OMAN', 'sort_order' => 174],
            ['code' => 'PAK', 'country' => 'PAKISTAN', 'sort_order' => 175],
            ['code' => 'PAN', 'country' => 'PANAMA', 'sort_order' => 176],
            ['code' => 'PCN', 'country' => 'PITCAIRN', 'sort_order' => 177],
            ['code' => 'PER', 'country' => 'PERU', 'sort_order' => 178],
            ['code' => 'PHL', 'country' => 'PHILIPPINES', 'sort_order' => 179],
            ['code' => 'PLW', 'country' => 'PALAU', 'sort_order' => 180],
            ['code' => 'PNG', 'country' => 'PAPUA NEW GUINEA', 'sort_order' => 181],
            ['code' => 'POL', 'country' => 'POLAND', 'sort_order' => 182],
            ['code' => 'PRI', 'country' => 'PUERTO RICO', 'sort_order' => 183],
            ['code' => 'PRK', 'country' => 'DEMOC.PEOPLES REP.OF KOREA', 'sort_order' => 184],
            ['code' => 'PRT', 'country' => 'PORTUGAL', 'sort_order' => 185],
            ['code' => 'PRY', 'country' => 'PARAGUAY', 'sort_order' => 186],
            ['code' => 'PSE', 'country' => 'PALESTINIAN TERRITORY, OCCUPIED', 'sort_order' => 187],
            ['code' => 'PYF', 'country' => 'FRENCH POLYNESIA', 'sort_order' => 188],
            ['code' => 'QAT', 'country' => 'QATAR', 'sort_order' => 189],
            ['code' => 'REU', 'country' => 'REUNION', 'sort_order' => 190],
            ['code' => 'ROU', 'country' => 'ROMANIA', 'sort_order' => 191],
            ['code' => 'RUS', 'country' => 'RUSSIAN FEDERATION (USSR)', 'sort_order' => 192],
            ['code' => 'RWA', 'country' => 'RWANDA', 'sort_order' => 193],
            ['code' => 'SAU', 'country' => 'SAUDI ARABIA', 'sort_order' => 194],
            ['code' => 'SCT', 'country' => 'SCOTLAND', 'sort_order' => 195],
            ['code' => 'SDN', 'country' => 'SUDAN', 'sort_order' => 196],
            ['code' => 'SEN', 'country' => 'SENEGAL', 'sort_order' => 197],
            ['code' => 'SGP', 'country' => 'SINGAPORE', 'sort_order' => 198],
            ['code' => 'SGS', 'country' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND', 'sort_order' => 199],
            ['code' => 'SHN', 'country' => 'ST. HELENA', 'sort_order' => 200],
            ['code' => 'SJM', 'country' => 'SVALBARD AND JAN MAYEN ISLANDS', 'sort_order' => 201],
            ['code' => 'SLB', 'country' => 'SOLOMON ISLANDS', 'sort_order' => 202],
            ['code' => 'SLE', 'country' => 'SIERRA LEONE', 'sort_order' => 203],
            ['code' => 'SLV', 'country' => 'EL SALVADOR', 'sort_order' => 204],
            ['code' => 'SMR', 'country' => 'SAN MARINO', 'sort_order' => 205],
            ['code' => 'SOM', 'country' => 'SOMALIA', 'sort_order' => 206],
            ['code' => 'SPM', 'country' => 'ST. PIERRE AND MIQUELON', 'sort_order' => 207],
            ['code' => 'SRB', 'country' => 'SERBIA', 'sort_order' => 208],
            ['code' => 'SSD', 'country' => 'SOUTH SUDAN', 'sort_order' => 209],
            ['code' => 'STP', 'country' => 'SAO TOME AND PRINCIPE', 'sort_order' => 210],
            ['code' => 'SUR', 'country' => 'SURINAME', 'sort_order' => 211],
            ['code' => 'SVK', 'country' => 'SLOVAK REPUBLIC', 'sort_order' => 212],
            ['code' => 'SVN', 'country' => 'SLOVENIA', 'sort_order' => 213],
            ['code' => 'SWE', 'country' => 'SWEDEN', 'sort_order' => 214],
            ['code' => 'SWZ', 'country' => 'ESWATINI, KINGDOM OF (SWAZILAND)', 'sort_order' => 215],
            ['code' => 'SXM', 'country' => 'SINT MAARTEN', 'sort_order' => 216],
            ['code' => 'SYC', 'country' => 'SEYCHELLES', 'sort_order' => 217],
            ['code' => 'SYR', 'country' => 'SYRIAN ARAB REPUBLIC', 'sort_order' => 218],
            ['code' => 'TCA', 'country' => 'TURKS AND CAICOS ISLANDS', 'sort_order' => 219],
            ['code' => 'TCD', 'country' => 'CHAD', 'sort_order' => 220],
            ['code' => 'TGO', 'country' => 'TOGO', 'sort_order' => 221],
            ['code' => 'THA', 'country' => 'THAILAND', 'sort_order' => 222],
            ['code' => 'TJK', 'country' => 'TAJIKISTAN', 'sort_order' => 223],
            ['code' => 'TKL', 'country' => 'TOKELAU', 'sort_order' => 224],
            ['code' => 'TKM', 'country' => 'TURKMENISTAN', 'sort_order' => 225],
            ['code' => 'TLS', 'country' => 'TIMOR-LESTE', 'sort_order' => 226],
            ['code' => 'TON', 'country' => 'TONGA', 'sort_order' => 227],
            ['code' => 'TTO', 'country' => 'TRINIDAD AND TOBAGO', 'sort_order' => 228],
            ['code' => 'TUN', 'country' => 'TUNISIA', 'sort_order' => 229],
            ['code' => 'TUR', 'country' => 'TURKIYE', 'sort_order' => 230],
            ['code' => 'TUV', 'country' => 'TUVALU', 'sort_order' => 231],
            ['code' => 'TWN', 'country' => 'TAIWAN', 'sort_order' => 232],
            ['code' => 'TZA', 'country' => 'TANZANIA UNITED REPUBLIC', 'sort_order' => 233],
            ['code' => 'UGA', 'country' => 'UGANDA', 'sort_order' => 234],
            ['code' => 'UKR', 'country' => 'UKRAINE', 'sort_order' => 235],
            ['code' => 'UMI', 'country' => 'UNITED STATES MINOR OUTLYING ISLANDS', 'sort_order' => 236],
            ['code' => 'URY', 'country' => 'URUGUAY', 'sort_order' => 237],
            ['code' => 'USA', 'country' => 'UNITED STATES OF AMERICA', 'sort_order' => 238],
            ['code' => 'UZB', 'country' => 'UZBEKISTAN', 'sort_order' => 239],
            ['code' => 'VAT', 'country' => 'VATICAN CITY STATE (HOLY SEE)', 'sort_order' => 240],
            ['code' => 'VCT', 'country' => 'SAINT VINCENT AND GRENADINES', 'sort_order' => 241],
            ['code' => 'VEN', 'country' => 'VENEZUELA', 'sort_order' => 242],
            ['code' => 'VGB', 'country' => 'VIRGIN ISLANDS(BRITISH)', 'sort_order' => 243],
            ['code' => 'VIR', 'country' => 'VIRGIN ISLANDS(US)', 'sort_order' => 244],
            ['code' => 'VNM', 'country' => 'VIETNAM', 'sort_order' => 245],
            ['code' => 'VUT', 'country' => 'VANUATU', 'sort_order' => 246],
            ['code' => 'WLF', 'country' => 'WALLIS AND FUTUNA ISLANDS', 'sort_order' => 247],
            ['code' => 'WSM', 'country' => 'SAMOA', 'sort_order' => 248],
            ['code' => 'XKX', 'country' => 'KOSOVO', 'sort_order' => 249],
            ['code' => 'YEM', 'country' => 'YEMEN', 'sort_order' => 250],
            ['code' => 'ZAF', 'country' => 'SOUTH AFRICA', 'sort_order' => 251],
            ['code' => 'ZMB', 'country' => 'ZAMBIA', 'sort_order' => 252],
            ['code' => 'ZWE', 'country' => 'ZIMBABWE', 'sort_order' => 253],
        ];

        foreach ($countries as $country) {
            \DB::table('countries')->updateOrInsert(
                ['code' => $country['code']],
                array_merge($country, [
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
