<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ['code' => 'AED', 'currency' => 'UAE Dirham', 'sort_order' => 1],
            ['code' => 'AFN', 'currency' => 'Afghani', 'sort_order' => 2],
            ['code' => 'ALL', 'currency' => 'Lek', 'sort_order' => 3],
            ['code' => 'AMD', 'currency' => 'Armenian Dram', 'sort_order' => 4],
            ['code' => 'ANG', 'currency' => 'Netherlands Antillean Guilder', 'sort_order' => 5],
            ['code' => 'AOA', 'currency' => 'Kwanza', 'sort_order' => 6],
            ['code' => 'ARS', 'currency' => 'Argentine Peso', 'sort_order' => 7],
            ['code' => 'AUD', 'currency' => 'Australian Dollar', 'sort_order' => 8],
            ['code' => 'AWG', 'currency' => 'Aruban Florin', 'sort_order' => 9],
            ['code' => 'AZN', 'currency' => 'Azerbaijan Manat', 'sort_order' => 10],
            ['code' => 'BAM', 'currency' => 'Convertible Mark', 'sort_order' => 11],
            ['code' => 'BBD', 'currency' => 'Barbados Dollar', 'sort_order' => 12],
            ['code' => 'BDT', 'currency' => 'Taka', 'sort_order' => 13],
            ['code' => 'BGN', 'currency' => 'Bulgarian Lev', 'sort_order' => 14],
            ['code' => 'BHD', 'currency' => 'Bahraini Dinar', 'sort_order' => 15],
            ['code' => 'BIF', 'currency' => 'Burundi Franc', 'sort_order' => 16],
            ['code' => 'BMD', 'currency' => 'Bermudian Dollar', 'sort_order' => 17],
            ['code' => 'BND', 'currency' => 'Brunei Dollar', 'sort_order' => 18],
            ['code' => 'BOB', 'currency' => 'Boliviano', 'sort_order' => 19],
            ['code' => 'BOV', 'currency' => 'Mvdol', 'sort_order' => 20],
            ['code' => 'BRL', 'currency' => 'Brazilian Real', 'sort_order' => 21],
            ['code' => 'BSD', 'currency' => 'Bahamian Dollar', 'sort_order' => 22],
            ['code' => 'BTN', 'currency' => 'Ngultrum', 'sort_order' => 23],
            ['code' => 'BWP', 'currency' => 'Pula', 'sort_order' => 24],
            ['code' => 'BYN', 'currency' => 'Belarusian Ruble', 'sort_order' => 25],
            ['code' => 'BZD', 'currency' => 'Belize Dollar', 'sort_order' => 26],
            ['code' => 'CAD', 'currency' => 'Canadian Dollar', 'sort_order' => 27],
            ['code' => 'CDF', 'currency' => 'Congolese Franc', 'sort_order' => 28],
            ['code' => 'CHE', 'currency' => 'WIR Euro', 'sort_order' => 29],
            ['code' => 'CHF', 'currency' => 'Swiss Franc', 'sort_order' => 30],
            ['code' => 'CHW', 'currency' => 'WIR Franc', 'sort_order' => 31],
            ['code' => 'CLF', 'currency' => 'Unidad de Fomento', 'sort_order' => 32],
            ['code' => 'CLP', 'currency' => 'Chilean Peso', 'sort_order' => 33],
            ['code' => 'CNH', 'currency' => 'Yuan Renminbi (International)', 'sort_order' => 34],
            ['code' => 'CNY', 'currency' => 'Yuan Renminbi (Domestic)', 'sort_order' => 35],
            ['code' => 'COP', 'currency' => 'Colombian Peso', 'sort_order' => 36],
            ['code' => 'COU', 'currency' => 'Unidad de Valor Real', 'sort_order' => 37],
            ['code' => 'CRC', 'currency' => 'Costa Rican Colon', 'sort_order' => 38],
            ['code' => 'CUC', 'currency' => 'Peso Convertible', 'sort_order' => 39],
            ['code' => 'CUP', 'currency' => 'Cuban Peso', 'sort_order' => 40],
            ['code' => 'CVE', 'currency' => 'Cabo Verde Escudo', 'sort_order' => 41],
            ['code' => 'CZK', 'currency' => 'Czech Koruna', 'sort_order' => 42],
            ['code' => 'DJF', 'currency' => 'Djibouti Franc', 'sort_order' => 43],
            ['code' => 'DKK', 'currency' => 'Danish Krone', 'sort_order' => 44],
            ['code' => 'DOP', 'currency' => 'Dominican Peso', 'sort_order' => 45],
            ['code' => 'DZD', 'currency' => 'Algerian Dinar', 'sort_order' => 46],
            ['code' => 'EGP', 'currency' => 'Egyptian Pound', 'sort_order' => 47],
            ['code' => 'ERN', 'currency' => 'Nakfa', 'sort_order' => 48],
            ['code' => 'ETB', 'currency' => 'Ethiopian Birr', 'sort_order' => 49],
            ['code' => 'EUR', 'currency' => 'Euro', 'sort_order' => 50],
            ['code' => 'FJD', 'currency' => 'Fiji Dollar', 'sort_order' => 51],
            ['code' => 'FKP', 'currency' => 'Falkland Islands Pound', 'sort_order' => 52],
            ['code' => 'GBP', 'currency' => 'Pound Sterling', 'sort_order' => 53],
            ['code' => 'GEL', 'currency' => 'Lari', 'sort_order' => 54],
            ['code' => 'GHS', 'currency' => 'Ghana Cedi', 'sort_order' => 55],
            ['code' => 'GIP', 'currency' => 'Gibraltar Pound', 'sort_order' => 56],
            ['code' => 'GMD', 'currency' => 'Dalasi', 'sort_order' => 57],
            ['code' => 'GNF', 'currency' => 'Guinean Franc', 'sort_order' => 58],
            ['code' => 'GTQ', 'currency' => 'Quetzal', 'sort_order' => 59],
            ['code' => 'GYD', 'currency' => 'Guyana Dollar', 'sort_order' => 60],
            ['code' => 'HKD', 'currency' => 'Hong Kong Dollar', 'sort_order' => 61],
            ['code' => 'HNL', 'currency' => 'Lempira', 'sort_order' => 62],
            ['code' => 'HRK', 'currency' => 'Kuna', 'sort_order' => 63],
            ['code' => 'HTG', 'currency' => 'Gourde', 'sort_order' => 64],
            ['code' => 'HUF', 'currency' => 'Forint', 'sort_order' => 65],
            ['code' => 'IDR', 'currency' => 'Rupiah', 'sort_order' => 66],
            ['code' => 'ILS', 'currency' => 'New Israeli Sheqel', 'sort_order' => 67],
            ['code' => 'INR', 'currency' => 'Indian Rupee', 'sort_order' => 68],
            ['code' => 'IQD', 'currency' => 'Iraqi Dinar', 'sort_order' => 69],
            ['code' => 'IRR', 'currency' => 'Iranian Rial', 'sort_order' => 70],
            ['code' => 'ISK', 'currency' => 'Iceland Krona', 'sort_order' => 71],
            ['code' => 'JMD', 'currency' => 'Jamaican Dollar', 'sort_order' => 72],
            ['code' => 'JOD', 'currency' => 'Jordanian Dinar', 'sort_order' => 73],
            ['code' => 'JPY', 'currency' => 'Yen', 'sort_order' => 74],
            ['code' => 'KES', 'currency' => 'Kenyan Shilling', 'sort_order' => 75],
            ['code' => 'KGS', 'currency' => 'Som', 'sort_order' => 76],
            ['code' => 'KHR', 'currency' => 'Riel', 'sort_order' => 77],
            ['code' => 'KMF', 'currency' => 'Comorian Franc', 'sort_order' => 78],
            ['code' => 'KPW', 'currency' => 'North Korean Won', 'sort_order' => 79],
            ['code' => 'KRW', 'currency' => 'Won', 'sort_order' => 80],
            ['code' => 'KWD', 'currency' => 'Kuwaiti Dinar', 'sort_order' => 81],
            ['code' => 'KYD', 'currency' => 'Cayman Islands Dollar', 'sort_order' => 82],
            ['code' => 'KZT', 'currency' => 'Tenge', 'sort_order' => 83],
            ['code' => 'LAK', 'currency' => 'Lao Kip', 'sort_order' => 84],
            ['code' => 'LBP', 'currency' => 'Lebanese Pound', 'sort_order' => 85],
            ['code' => 'LKR', 'currency' => 'Sri Lanka Rupee', 'sort_order' => 86],
            ['code' => 'LRD', 'currency' => 'Liberian Dollar', 'sort_order' => 87],
            ['code' => 'LSL', 'currency' => 'Loti', 'sort_order' => 88],
            ['code' => 'LYD', 'currency' => 'Libyan Dinar', 'sort_order' => 89],
            ['code' => 'MAD', 'currency' => 'Moroccan Dirham', 'sort_order' => 90],
            ['code' => 'MDL', 'currency' => 'Moldovan Leu', 'sort_order' => 91],
            ['code' => 'MGA', 'currency' => 'Malagasy Ariary', 'sort_order' => 92],
            ['code' => 'MKD', 'currency' => 'Denar', 'sort_order' => 93],
            ['code' => 'MMK', 'currency' => 'Kyat', 'sort_order' => 94],
            ['code' => 'MNT', 'currency' => 'Tugrik', 'sort_order' => 95],
            ['code' => 'MOP', 'currency' => 'Pataca', 'sort_order' => 96],
            ['code' => 'MRU', 'currency' => 'Ouguiya', 'sort_order' => 97],
            ['code' => 'MUR', 'currency' => 'Mauritius Rupee', 'sort_order' => 98],
            ['code' => 'MVR', 'currency' => 'Rufiyaa', 'sort_order' => 99],
            ['code' => 'MWK', 'currency' => 'Malawi Kwacha', 'sort_order' => 100],
            ['code' => 'MXN', 'currency' => 'Mexican Peso', 'sort_order' => 101],
            ['code' => 'MXV', 'currency' => 'Mexican Unidad de Inversion (UDI)', 'sort_order' => 102],
            ['code' => 'MYR', 'currency' => 'Malaysian Ringgit', 'sort_order' => 103],
            ['code' => 'MZN', 'currency' => 'Mozambique Metical', 'sort_order' => 104],
            ['code' => 'NAD', 'currency' => 'Namibia Dollar', 'sort_order' => 105],
            ['code' => 'NGN', 'currency' => 'Naira', 'sort_order' => 106],
            ['code' => 'NIO', 'currency' => 'Cordoba Oro', 'sort_order' => 107],
            ['code' => 'NOK', 'currency' => 'Norwegian Krone', 'sort_order' => 108],
            ['code' => 'NPR', 'currency' => 'Nepalese Rupee', 'sort_order' => 109],
            ['code' => 'NZD', 'currency' => 'New Zealand Dollar', 'sort_order' => 110],
            ['code' => 'OMR', 'currency' => 'Rial Omani', 'sort_order' => 111],
            ['code' => 'PAB', 'currency' => 'Balboa', 'sort_order' => 112],
            ['code' => 'PEN', 'currency' => 'Sol', 'sort_order' => 113],
            ['code' => 'PGK', 'currency' => 'Kina', 'sort_order' => 114],
            ['code' => 'PHP', 'currency' => 'Philippine Peso', 'sort_order' => 115],
            ['code' => 'PKR', 'currency' => 'Pakistan Rupee', 'sort_order' => 116],
            ['code' => 'PLN', 'currency' => 'Zloty', 'sort_order' => 117],
            ['code' => 'PYG', 'currency' => 'Guarani', 'sort_order' => 118],
            ['code' => 'QAR', 'currency' => 'Qatari Rial', 'sort_order' => 119],
            ['code' => 'RON', 'currency' => 'Romanian Leu', 'sort_order' => 120],
            ['code' => 'RSD', 'currency' => 'Serbian Dinar', 'sort_order' => 121],
            ['code' => 'RUB', 'currency' => 'Russian Ruble', 'sort_order' => 122],
            ['code' => 'RWF', 'currency' => 'Rwanda Franc', 'sort_order' => 123],
            ['code' => 'SAR', 'currency' => 'Saudi Riyal', 'sort_order' => 124],
            ['code' => 'SBD', 'currency' => 'Solomon Islands Dollar', 'sort_order' => 125],
            ['code' => 'SCR', 'currency' => 'Seychelles Rupee', 'sort_order' => 126],
            ['code' => 'SDG', 'currency' => 'Sudanese Pound', 'sort_order' => 127],
            ['code' => 'SEK', 'currency' => 'Swedish Krona', 'sort_order' => 128],
            ['code' => 'SGD', 'currency' => 'Singapore Dollar', 'sort_order' => 129],
            ['code' => 'SHP', 'currency' => 'Saint Helena Pound', 'sort_order' => 130],
            ['code' => 'SLL', 'currency' => 'Leone', 'sort_order' => 131],
            ['code' => 'SOS', 'currency' => 'Somali Shilling', 'sort_order' => 132],
            ['code' => 'SRD', 'currency' => 'Surinam Dollar', 'sort_order' => 133],
            ['code' => 'SSP', 'currency' => 'South Sudanese Pound', 'sort_order' => 134],
            ['code' => 'STN', 'currency' => 'Dobra', 'sort_order' => 135],
            ['code' => 'SVC', 'currency' => 'El Salvador Colon', 'sort_order' => 136],
            ['code' => 'SYP', 'currency' => 'Syrian Pound', 'sort_order' => 137],
            ['code' => 'SZL', 'currency' => 'Lilangeni', 'sort_order' => 138],
            ['code' => 'THB', 'currency' => 'Baht', 'sort_order' => 139],
            ['code' => 'TJS', 'currency' => 'Somoni', 'sort_order' => 140],
            ['code' => 'TMT', 'currency' => 'Turkmenistan New Manat', 'sort_order' => 141],
            ['code' => 'TND', 'currency' => 'Tunisian Dinar', 'sort_order' => 142],
            ['code' => 'TOP', 'currency' => 'Pa\'anga', 'sort_order' => 143],
            ['code' => 'TRY', 'currency' => 'Turkish Lira', 'sort_order' => 144],
            ['code' => 'TTD', 'currency' => 'Trinidad and Tobago Dollar', 'sort_order' => 145],
            ['code' => 'TWD', 'currency' => 'New Taiwan Dollar', 'sort_order' => 146],
            ['code' => 'TZS', 'currency' => 'Tanzanian Shilling', 'sort_order' => 147],
            ['code' => 'UAH', 'currency' => 'Hryvnia', 'sort_order' => 148],
            ['code' => 'UGX', 'currency' => 'Uganda Shilling', 'sort_order' => 149],
            ['code' => 'USD', 'currency' => 'US Dollar', 'sort_order' => 150],
            ['code' => 'USN', 'currency' => 'US Dollar (Next day)', 'sort_order' => 151],
            ['code' => 'UYI', 'currency' => 'Uruguay Peso en Unidades Indexadas (UI)', 'sort_order' => 152],
            ['code' => 'UYU', 'currency' => 'Peso Uruguayo', 'sort_order' => 153],
            ['code' => 'UYW', 'currency' => 'Unidad Previsional', 'sort_order' => 154],
            ['code' => 'UZS', 'currency' => 'Uzbekistan Sum', 'sort_order' => 155],
            ['code' => 'VED', 'currency' => 'Bolívar Soberano', 'sort_order' => 156],
            ['code' => 'VES', 'currency' => 'Bolívar Soberano', 'sort_order' => 157],
            ['code' => 'VND', 'currency' => 'Dong', 'sort_order' => 158],
            ['code' => 'VUV', 'currency' => 'Vatu', 'sort_order' => 159],
            ['code' => 'WST', 'currency' => 'Tala', 'sort_order' => 160],
            ['code' => 'XAF', 'currency' => 'CFA Franc BEAC', 'sort_order' => 161],
            ['code' => 'XAG', 'currency' => 'Silver', 'sort_order' => 162],
            ['code' => 'XAU', 'currency' => 'Gold', 'sort_order' => 163],
            ['code' => 'XBA', 'currency' => 'Bond Markets Unit European Composite Unit (EURCO)', 'sort_order' => 164],
            ['code' => 'XBB', 'currency' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'sort_order' => 165],
            ['code' => 'XBC', 'currency' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'sort_order' => 166],
            ['code' => 'XBD', 'currency' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'sort_order' => 167],
            ['code' => 'XCD', 'currency' => 'East Caribbean Dollar', 'sort_order' => 168],
            ['code' => 'XDR', 'currency' => 'SDR (Special Drawing Right)', 'sort_order' => 169],
            ['code' => 'XOF', 'currency' => 'CFA Franc BCEAO', 'sort_order' => 170],
            ['code' => 'XPD', 'currency' => 'Palladium', 'sort_order' => 171],
            ['code' => 'XPF', 'currency' => 'CFP Franc', 'sort_order' => 172],
            ['code' => 'XPT', 'currency' => 'Platinum', 'sort_order' => 173],
            ['code' => 'XSU', 'currency' => 'Sucre', 'sort_order' => 174],
            ['code' => 'XUA', 'currency' => 'ADB Unit of Account', 'sort_order' => 175],
            ['code' => 'XXX', 'currency' => 'The codes assigned for transactions where no currency is involved', 'sort_order' => 176],
            ['code' => 'YER', 'currency' => 'Yemeni Rial', 'sort_order' => 177],
            ['code' => 'ZAR', 'currency' => 'Rand', 'sort_order' => 178],
            ['code' => 'ZMW', 'currency' => 'Zambian Kwacha', 'sort_order' => 179],
            ['code' => 'ZWL', 'currency' => 'Zimbabwe Dollar', 'sort_order' => 180],
        ];

        foreach ($currencies as $currency) {
            \DB::table('currencies')->updateOrInsert(
                ['code' => $currency['code']],
                array_merge($currency, [
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
